openapi: 3.0.0
info:
  title: hotel
  version: '1.0'
  contact:
    name: masashi mizuno
  description: |-
    Hotel向けAPI
    認証はCognitoが発行したJWT Tokenを利用する
servers:
  - url: 'https://satellite-office-app.herokuapp.com'
    description: Mock
  - url: 'https://{本番ドメイン}/hotel/api/v1'
    description: Production
paths:
  /hotel/login:
    post:
      summary: ログイン
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  hotel_id:
                    type: number
                    description: ログインしたユーザーのID
                    example: 100
                  hotel_name:
                    type: string
                    description: ユーザー名
                    example: 鈴木太郎
                  token:
                    type: string
                    description: アクセストークン
                    format: string
                    example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuWxseeUsCIsImV4cCI6IjIwMTkvMDQvMDEifQ.u8TT4ySJhBiMod1rNqCxiISXwCXqddVSJE5gncSCGD7RPHigHoZiDnLfwcIIGij-ARBrswe4eluMUgaQwS7FUdN8IVwKkFUY1533TQZZYhTUzobO3q_PnDyPi8cPDmkSTJHzBhT298G7fNZENUUo8fmCjOkYC9FibTMrF6Aij4w
                required:
                  - hotel_id
                  - hotel_name
                  - token
              examples:
                Example:
                  value:
                    hotel_id: 1
                    hotel_name: ホテルA
                    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuWxseeUsCIsImV4cCI6IjIwMTkvMDQvMDEifQ.u8TT4ySJhBiMod1rNqCxiISXwCXqddVSJE5gncSCGD7RPHigHoZiDnLfwcIIGij-ARBrswe4eluMUgaQwS7FUdN8IVwKkFUY1533TQZZYhTUzobO3q_PnDyPi8cPDmkSTJHzBhT298G7fNZENUUo8fmCjOkYC9FibTMrF6Ai
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-login
      description: Cognitoを利用した認証を行う
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 登録メールアドレス
                password:
                  type: string
                  description: ログインパスワード
              required:
                - email
                - password
        description: ''
      tags:
        - 認証
    parameters: []
  /hotel/info:
    get:
      summary: ホテル情報
      tags:
        - ホテル
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    description: ホテルID
                  name:
                    type: string
                    description: ホテル名
                  name_kana:
                    type: string
                    description: ホテル名カナ
                  address:
                    type: string
                    description: 住所
                  tel:
                    type: string
                    description: 電話番号
                  contract_number:
                    type: string
                    description: 契約番号
                  url:
                    type: string
                    description: URL
                  area_id:
                    type: number
                    description: エリアコード
                  station:
                    type: string
                    description: 最寄り駅
                  access:
                    type: string
                    description: 交通アクセス
                  parking:
                    type: string
                    description: 駐車場
                  status:
                    type: number
                    description: |-
                      0: 停止
                      1: 利用可能
                required:
                  - id
                  - name
                  - name_kana
                  - address
                  - tel
                  - contract_number
                  - area_id
                  - status
              examples:
                example:
                  value:
                    id: 1
                    name: ホテルA
                    name_kane: ホテルエー
                    address: 東京都品川区
                    tel: 03-0000-1111
                    contract_number: JS-H-022790086075
                    url: 'https://xxx.com'
                    area_id: 100
                    station: 品川駅
                    access: ＪＲ線品川駅（高輪口）より徒歩２分
                    parking: '有り　1,500円（税込み）　先着順'
                    status: 1
      operationId: get-hotel-info
      description: ホテル情報取得API
      security:
        - bearerAuth: []
  /hotel/edit:
    post:
      summary: ホテル情報編集
      tags:
        - ホテル
      responses:
        '200':
          description: OK
      operationId: get-hotel-edit
      description: ホテル情報編集API
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ホテル名
                name_kana:
                  type: string
                  description: ホテル名カナ
                address:
                  type: string
                  description: 住所
                tel:
                  type: string
                  description: 電話番号
                url:
                  type: string
                  description: URL
                area_id:
                  type: number
                  description: エリアコード
                station:
                  type: string
                  description: 最寄り駅
                access:
                  type: string
                  description: 交通アクセス
                parking:
                  type: string
                  description: 駐車場                
              required:
                - area_id
                - tel
                - address
                - name_kana
                - name
components:
  schemas: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: Bearer
tags:
  - name: 認証
    description: ログインに関わるAPI
  - name: ホテル
    description: ホテルAPI
