openapi: 3.0.0
info:
  title: user
  version: '1.0'
  contact:
    name: masashi mizuno
  description: |-
    User向けAPI
    認証はCognitoが発行したJWT Tokenを利用する
servers:
  - url: 'https://satellite-office-app.herokuapp.com'
paths:
  /login:
    post:
      summary: login
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    description: ログインしたユーザーのID
                  user_name:
                    type: string
                    description: ユーザー名
                  token:
                    type: string
                    description: アクセストークン
                  is_unauth_user:
                    type: boolean
                    description: |-
                      初回ログインユーザーかどうか
                      初回だった場合はパスワード変更させる
                required:
                  - user_id
                  - user_name
                  - token
                  - is_unauth_user
              examples:
                user_id:
                  value: 1
                user_name:
                  value: 太郎
                token:
                  value: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuWxseeUsCIsImV4cCI6IjIwMTkvMDQvMDEifQ.u8TT4ySJhBiMod1rNqCxiISXwCXqddVSJE5gncSCGD7RPHigHoZiDnLfwcIIGij-ARBrswe4eluMUgaQwS7FUdN8IVwKkFUY1533TQZZYhTUzobO3q_PnDyPi8cPDmkSTJHzBhT298G7fNZENUUo8fmCjOkYC9FibTMrF6Aij4w
                is_unauth_user:
                  value: true
      operationId: post-login
      description: Cognitoを利用した認証を行う
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 登録メールアドレス
                password:
                  type: string
                  description: ログインパスワード
              required:
                - email
                - password
      tags:
        - login
  /change_password:
    post:
      summary: change_password
      responses:
        '200':
          description: OK
      operationId: post-change_password
      description: パスワード変更を行う。初回パスワード設定も
      security:
        - Authorization: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                old_password:
                  type: string
                  description: 旧パスワード
                new_password:
                  type: string
                  description: 新パスワード
              required:
                - old_password
                - new_password
        description: ''
      tags:
        - login
components:
  schemas: {}
  securitySchemes:
    Authorization:
      name: bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuWxseeUsCIsImV4cCI6IjIwMTkvMDQvMDEifQ.u8TT4ySJhBiMod1rNqCxiISXwCXqddVSJE5gncSCGD7RPHigHoZiDnLfwcIIGij-ARBrswe4eluMUgaQwS7FUdN8IVwKkFUY1533TQZZYhTUzobO3q_PnDyPi8cPDmkSTJHzBhT298G7fNZENUUo8fmCjOkYC9FibTMrF6Aij4w
      type: apiKey
      in: header
