openapi: 3.0.0
info:
  title: user
  version: '1.0'
  contact:
    name: masashi mizuno
  description: |-
    User向けAPI
    認証はCognitoが発行したJWT Tokenを利用する
servers:
  - url: 'https://satellite-office-app.herokuapp.com'
paths:
  /login:
    post:
      summary: ログイン
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: number
                    description: ログインしたユーザーのID
                    example: 100
                  user_name:
                    type: string
                    description: ユーザー名
                    example: 鈴木太郎
                  token:
                    type: string
                    description: アクセストークン
                    format: string
                    example: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuWxseeUsCIsImV4cCI6IjIwMTkvMDQvMDEifQ.u8TT4ySJhBiMod1rNqCxiISXwCXqddVSJE5gncSCGD7RPHigHoZiDnLfwcIIGij-ARBrswe4eluMUgaQwS7FUdN8IVwKkFUY1533TQZZYhTUzobO3q_PnDyPi8cPDmkSTJHzBhT298G7fNZENUUo8fmCjOkYC9FibTMrF6Aij4w
                  is_unauth_user:
                    type: boolean
                    description: |-
                      初回ログインユーザーかどうか
                      初回だった場合はパスワード変更させる
                    example: true
                required:
                  - user_id
                  - user_name
                  - token
                  - is_unauth_user
              examples:
                Example:
                  value:
                    user_id: 1
                    user_name: 太郎
                    token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IuWxseeUsCIsImV4cCI6IjIwMTkvMDQvMDEifQ.u8TT4ySJhBiMod1rNqCxiISXwCXqddVSJE5gncSCGD7RPHigHoZiDnLfwcIIGij-ARBrswe4eluMUgaQwS7FUdN8IVwKkFUY1533TQZZYhTUzobO3q_PnDyPi8cPDmkSTJHzBhT298G7fNZENUUo8fmCjOkYC9FibTMrF6Ai
                    is_unauth_user: true
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-login
      description: Cognitoを利用した認証を行う
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 登録メールアドレス
                password:
                  type: string
                  description: ログインパスワード
              required:
                - email
                - password
        description: ''
      tags:
        - ユーザー認証
  /change_password:
    post:
      summary: パスワード変更
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-change_password
      description: パスワード変更を行う。初回パスワード設定も
      security:
        - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                old_password:
                  type: string
                  description: 旧パスワード
                new_password:
                  type: string
                  description: 新パスワード
              required:
                - old_password
                - new_password
        description: ''
      tags:
        - ユーザー認証
  /reset_password:
    post:
      summary: パスワードリセット
      tags:
        - ユーザー認証
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: post-reset_password
      description: パスワードリセットを行う
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      security:
        - bearerAuth: []
  /areas:
    get:
      summary: エリア一覧取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                description: エリア一覧
                properties:
                  areas:
                    type: array
                    description: エリアリスト
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: エリアID
                        name:
                          type: string
                          description: エリア名
                        stations:
                          type: array
                          description: エリア内の駅リスト
                          items:
                            type: object
                            description: ''
                            properties:
                              id:
                                type: string
                                description: 駅ID
                              name:
                                type: string
                                description: 駅名
                            required:
                              - id
                              - name
              examples:
                example:
                  value:
                    areas:
                      - id: 1
                        name: 品川
                        stations:
                          - id: 1
                            name: 品川駅
                          - id: 2
                            name: 北品川駅
                          - id: 3
                            name: 高輪台駅
                      - id: 2
                        name: 渋谷
                        stations:
                          - id: 1
                            name: 品川駅
                          - id: 2
                            name: 神泉駅
                          - id: 3
                            name: 代官山駅
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: ../models/error.v1.yaml
      operationId: get-areas
      description: エリア一覧を取得する
      tags:
        - 施設関連
      security:
        - bearerAuth: []
components:
  schemas: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: Bearer
      description: ''
tags:
  - name: ユーザー認証
    description: ユーザーログインに関わるAPI
  - name: 施設関連
    description: 施設関連
