name: Stoplight Publish

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, publish
      run: |
        mkdir ~/.npm-global
        npm config set prefix '~/.npm-global'
        echo ' export PATH=~/.npm-global/bin:$PATH' >> ~/.bash_profile
        source ~/.bash_profile
        npm i -g @stoplight/cli
        stoplight publish --token 2XyfAMrDJHEknBn898 --url https://stoplight.io/api
      env:
        CI: true
