name: Stoplight Publish

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, publish
      run: |
        npm install
        ln -s /usr/bin/nodejs /usr/bin/node
        ls -la
        pwd
        node_modules/@stoplight/cli/bin/stoplight.js publish --token 2XyfAMrDJHEknBn898 --url https://stoplight.io/api
      env:
        CI: true
